#!/usr/bin/env node
// Reads Terraform state at build time and writes
// app/packages/server/src/generated/tfstate.ts with the parsed state
// embedded as a JSON literal. ConfigService imports it as a fallback when the
// state file is not present at runtime (e.g. dev without a terraform apply).
//
// State resolution order:
//   1. First CLI argument (path to a local tfstate file)
//        node scripts/embed-tfstate.mjs /path/to/terraform.tfstate
//   2. TF_STATE_PATH env var (path to a local tfstate file)
//        TF_STATE_PATH=/path/to/terraform.tfstate npm run build
//   3. Default: run `terraform state pull` from <repo-root>/terraform/
//      This works for any backend (local file or remote S3/GCS/etc.) as long
//      as `terraform` is on PATH and AWS credentials are available.

import { readFileSync, writeFileSync, mkdirSync } from 'fs';
import { join, resolve, dirname } from 'path';
import { fileURLToPath } from 'url';
import { execSync } from 'child_process';

const __dirname = dirname(fileURLToPath(import.meta.url));

function getRepoRoot() {
  try {
    // --git-common-dir returns the main .git directory in both the main
    // working tree (as a relative path) and git worktrees (as an absolute
    // path). Resolving it against __dirname makes it absolute in both cases.
    const commonDir = execSync('git rev-parse --git-common-dir', {
      encoding: 'utf-8',
      cwd: __dirname,
    }).trim();
    return resolve(__dirname, commonDir, '..');
  } catch {
    return resolve(__dirname, '../..');
  }
}

const outDir = join(__dirname, '../packages/server/src/generated');
const outPath = join(outDir, 'tfstate.ts');

mkdirSync(outDir, { recursive: true });

function writeStub(json) {
  writeFileSync(
    outPath,
    `// Auto-generated by scripts/embed-tfstate.mjs — do not edit by hand\n` +
    `export const EMBEDDED_TFSTATE: Record<string, unknown> | null = ${json};\n`,
  );
}

function embedFromFile(filePath) {
  const raw = JSON.parse(readFileSync(filePath, 'utf-8'));
  writeStub(JSON.stringify(raw));
  console.log(`[embed-tfstate] Embedded state from ${filePath}`);
}

// --- Resolution ---

if (process.argv[2] || process.env.TF_STATE_PATH) {
  const filePath = resolve(process.argv[2] ?? process.env.TF_STATE_PATH);
  try {
    embedFromFile(filePath);
  } catch (err) {
    console.error(`[embed-tfstate] Failed to read ${filePath}:`, err.message);
    writeStub('null');
    process.exit(1);
  }
  process.exit(0);
}

// Default: pull live state from the configured backend via `terraform state pull`
const tfDir = join(getRepoRoot(), 'terraform');
console.log(`[embed-tfstate] Running 'terraform state pull' in ${tfDir} ...`);
try {
  const raw = execSync('terraform state pull', {
    encoding: 'utf-8',
    cwd: tfDir,
    stdio: ['inherit', 'pipe', 'inherit'],
  });
  const parsed = JSON.parse(raw);
  writeStub(JSON.stringify(parsed));
  console.log('[embed-tfstate] Embedded live Terraform state');
} catch (err) {
  console.warn(`[embed-tfstate] 'terraform state pull' failed — embedding null. (${err.message})`);
  writeStub('null');
  // Non-fatal: the server will degrade gracefully without state
}
